AWSTemplateFormatVersion: '2010-09-09'
Description: Sales Data Processing and Notification System

Parameters:
  
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  EmailSubscriber:
    Type: String
    Description: Email address to receive sales notifications

Resources: