AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function deployment from S3 and Lambda function to process sales data, connect to RDS, use Secrets Manager, send notifications via SNS, and run on CloudWatch schedule
Parameters:
  LambdaFunctionName:
    Type: String
    Default: SalesProcessorFunction
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      Role: !ImportValue MyStack-LambdaExecutionRoleArn
      Code:
        S3Bucket: your bucket name 
        S3Key: lambda_code.zip
      Timeout: 60
      Environment:
        Variables:
          SECRET_ARN: !ImportValue MyStack-RDSSecret
          DB_NAME: !ImportValue SalesDBName
          RDS_HOST: !ImportValue SalesDBEndpoint
          SNS_TOPIC_ARN: !ImportValue SalesSNSTopicArn
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue LambdaSecurityGroupId
        SubnetIds:
          - !ImportValue MyStack-PrivateSubnet1
          - !ImportValue MyStack-PrivateSubnet2





Outputs:
  LambdaFunctionArn:
    Value: !GetAtt MyLambdaFunction.Arn
    Export:
      Name: SalesProcessorFunctionArn

