AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Lambda to access RDS, Secrets Manager, CloudWatch Logs, and S3

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaS3RDSExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaFullPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:*
                  - secretsmanager:GetSecretValue
                  - sns:Publish
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetObject
                  - s3:ListBucket
                  - ec2:CreateNetworkInterface  
                  - ec2:DescribeNetworkInterfaces   
                  - ec2:DeleteNetworkInterface
                Resource: '*'
Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: MyStack-LambdaExecutionRoleArn
