AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager for RDS credentials

Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSSecret
      Description: RDS Credentials
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}"
        }

Outputs:
  DBSecretArn:
    Value: !Ref DBSecret
    Export:
      Name: MyStack-RDSSecret
